import { MongoClient } from 'mongodb'
import { mongoCollections } from '~/src/helpers/constants'
import {
  createDocument,
  readAllDocuments,
  readDocument
} from '~/src/helpers/databaseTransaction'

import config from '~/src/config'


const { disinfectantApprovedListSI } = mongoCollections

const sampleData = {
  "@odata.context": "https://org5d77c363.api.crm11.dynamics.com/api/data/v9.2/$metadata#dsf_approvalslistsis",
  "@odata.count": 34,
  "value": [
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05c1",
          "dsf_chemicalgroups": "Peracetic acid; Hydrogen peroxide",
          "dsf_companyaddress": "1 Main Street, Cityville, CV1 1AA",
          "dsf_companyname": "AlphaTech Ltd",
          "dsf_disinfectant": "AlphaClean",
          "dsf_disinfectantname": "AlphaClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "100",
          "dsf_fm_approveddilution": "200",
          "dsf_go_approveddilution": "300",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "AlphaClean",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "400",
          "dsf_tb_approveddilution": "500",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05c2",
          "dsf_chemicalgroups": "Sodium hypochlorite; Quaternary ammonium compounds",
          "dsf_companyaddress": "2 Market Square, Townsville, TS2 2BB",
          "dsf_companyname": "BetaBio Corp",
          "dsf_disinfectant": "BetaGuard",
          "dsf_disinfectantname": "BetaGuard",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "110",
          "dsf_fm_approveddilution": "220",
          "dsf_go_approveddilution": "330",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "BetaGuard",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "440",
          "dsf_tb_approveddilution": "550",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05d1",
          "dsf_chemicalgroups": "Chlorine dioxide; Hydrogen peroxide",
          "dsf_companyaddress": "11 Bio Street, GreenCity, GC11 11KK",
          "dsf_companyname": "BioGuard Inc",
          "dsf_disinfectant": "BioClean",
          "dsf_disinfectantname": "BioClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "200",
          "dsf_fm_approveddilution": "310",
          "dsf_go_approveddilution": "420",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "BioClean",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "530",
          "dsf_tb_approveddilution": "640",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05c4",
          "dsf_chemicalgroups": "Peroxymonosulphate; Quaternary ammonium compounds",
          "dsf_companyaddress": "4 Tech Drive, Innovatetown, IT4 4DD",
          "dsf_companyname": "DeltaDisinfect Ltd",
          "dsf_disinfectant": "DeltaShield",
          "dsf_disinfectantname": "DeltaShield",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "130",
          "dsf_fm_approveddilution": "240",
          "dsf_go_approveddilution": "350",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "DeltaShield",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "460",
          "dsf_tb_approveddilution": "570",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05c5",
          "dsf_chemicalgroups": "Hydrogen peroxide; Phenolic compounds",
          "dsf_companyaddress": "5 Business Way, Commerce City, CC5 5EE",
          "dsf_companyname": "EpsilonEco",
          "dsf_disinfectant": "EpsilonClean",
          "dsf_disinfectantname": "EpsilonClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "140",
          "dsf_fm_approveddilution": "250",
          "dsf_go_approveddilution": "360",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "EpsilonClean",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "470",
          "dsf_tb_approveddilution": "580",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05c3",
          "dsf_chemicalgroups": "Chlorine dioxide; Phenolic compounds",
          "dsf_companyaddress": "3 Industrial Park, Villageton, VT3 3CC",
          "dsf_companyname": "GammaClean Solutions",
          "dsf_disinfectant": "GammaSafe",
          "dsf_disinfectantname": "GammaSafe",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "120",
          "dsf_fm_approveddilution": "230",
          "dsf_go_approveddilution": "340",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "GammaSafe",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "450",
          "dsf_tb_approveddilution": "560",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05c6",
          "dsf_chemicalgroups": "Sodium hypochlorite; Peracetic acid",
          "dsf_companyaddress": "6 Avenue Park, Metro City, MC6 6FF",
          "dsf_companyname": "ZetaSafe Inc",
          "dsf_disinfectant": "ZetaClean",
          "dsf_disinfectantname": "ZetaClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "150",
          "dsf_fm_approveddilution": "260",
          "dsf_go_approveddilution": "370",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "ZetaClean",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "480",
          "dsf_tb_approveddilution": "590",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05c7",
          "dsf_chemicalgroups": "Peracetic acid; Sodium hypochlorite",
          "dsf_companyaddress": "7 Industry Lane, Techville, TV7 7GG",
          "dsf_companyname": "ZetaBio Corp",
          "dsf_disinfectant": "ZetaGuard",
          "dsf_disinfectantname": "ZetaGuard",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "160",
          "dsf_fm_approveddilution": "270",
          "dsf_go_approveddilution": "380",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "ZetaGuard",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "490",
          "dsf_tb_approveddilution": "600",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05c8",
          "dsf_chemicalgroups": "Quaternary ammonium compounds; Phenolic compounds",
          "dsf_companyaddress": "8 Commerce Street, Tradeville, TV8 8HH",
          "dsf_companyname": "OmicronSafe Ltd",
          "dsf_disinfectant": "OmicronClean",
          "dsf_disinfectantname": "OmicronClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "170",
          "dsf_fm_approveddilution": "280",
          "dsf_go_approveddilution": "390",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "OmicronClean",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "500",
          "dsf_tb_approveddilution": "610",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05c9",
          "dsf_chemicalgroups": "Hydrogen peroxide; Chlorine dioxide",
          "dsf_companyaddress": "9 Innovation Drive, Creativille, CV9 9II",
          "dsf_companyname": "SigmaSolutions Inc",
          "dsf_disinfectant": "SigmaGuard",
          "dsf_disinfectantname": "SigmaGuard",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "180",
          "dsf_fm_approveddilution": "290",
          "dsf_go_approveddilution": "400",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "SigmaGuard",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "510",
          "dsf_tb_approveddilution": "620",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05d2",
          "dsf_chemicalgroups": "Peracetic acid; Hydrogen peroxide",
          "dsf_companyaddress": "12 Commerce Blvd, TradeCity, TC12 12LL",
          "dsf_companyname": "KappaKleen Ltd",
          "dsf_disinfectant": "KappaGuard",
          "dsf_disinfectantname": "KappaGuard",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "210",
          "dsf_fm_approveddilution": "320",
          "dsf_go_approveddilution": "430",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "KappaGuard",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "540",
          "dsf_tb_approveddilution": "650",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05d3",
          "dsf_chemicalgroups": "Quaternary ammonium compounds; Phenolic compounds",
          "dsf_companyaddress": "13 Tech Park, Innovate City, IC13 13MM",
          "dsf_companyname": "NuClean Solutions",
          "dsf_disinfectant": "NuGuard",
          "dsf_disinfectantname": "NuGuard",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "220",
          "dsf_fm_approveddilution": "330",
          "dsf_go_approveddilution": "440",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "NuGuard",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "550",
          "dsf_tb_approveddilution": "660",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05d4",
          "dsf_chemicalgroups": "Hydrogen peroxide; Sodium hypochlorite",
          "dsf_companyaddress": "14 Industrial Estate, Manufacture Town, MT14 14NN",
          "dsf_companyname": "Phoenix Chemicals",
          "dsf_disinfectant": "PhoenixGuard",
          "dsf_disinfectantname": "PhoenixGuard",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "230",
          "dsf_fm_approveddilution": "340",
          "dsf_go_approveddilution": "450",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "PhoenixGuard",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "560",
          "dsf_tb_approveddilution": "670",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05d5",
          "dsf_chemicalgroups": "Peracetic acid; Quaternary ammonium compounds",
          "dsf_companyaddress": "15 Research Road, Innovate City, IC15 15OO",
          "dsf_companyname": "Quantum Disinfectants",
          "dsf_disinfectant": "QuantumClean",
          "dsf_disinfectantname": "QuantumClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "240",
          "dsf_fm_approveddilution": "350",
          "dsf_go_approveddilution": "460",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "QuantumClean",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "570",
          "dsf_tb_approveddilution": "680",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05d6",
          "dsf_chemicalgroups": "Chlorine dioxide; Phenolic compounds",
          "dsf_companyaddress": "16 Innovation Street, Research Town, RT16 16PP",
          "dsf_companyname": "Radiant Solutions",
          "dsf_disinfectant": "RadiantGuard",
          "dsf_disinfectantname": "RadiantGuard",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "250",
          "dsf_fm_approveddilution": "360",
          "dsf_go_approveddilution": "470",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "RadiantGuard",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "580",
          "dsf_tb_approveddilution": "690",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05d7",
          "dsf_chemicalgroups": "Hydrogen peroxide; Sodium hypochlorite",
          "dsf_companyaddress": "17 Biotech Park, Green Town, GT17 17QQ",
          "dsf_companyname": "Sterile Solutions",
          "dsf_disinfectant": "SterileClean",
          "dsf_disinfectantname": "SterileClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "260",
          "dsf_fm_approveddilution": "370",
          "dsf_go_approveddilution": "480",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "SterileClean",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "590",
          "dsf_tb_approveddilution": "700",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05d8",
          "dsf_chemicalgroups": "Quaternary ammonium compounds; Phenolic compounds",
          "dsf_companyaddress": "18 Eco Drive, Sustainable City, SC18 18RR",
          "dsf_companyname": "UltraGuard Inc",
          "dsf_disinfectant": "UltraClean",
          "dsf_disinfectantname": "UltraClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "270",
          "dsf_fm_approveddilution": "380",
          "dsf_go_approveddilution": "490",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "UltraClean",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "600",
          "dsf_tb_approveddilution": "710",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05d9",
          "dsf_chemicalgroups": "Hydrogen peroxide; Chlorine dioxide",
          "dsf_companyaddress": "19 Tech Avenue, Innovation City, IC19 19SS",
          "dsf_companyname": "Vanguard Solutions",
          "dsf_disinfectant": "VanguardGuard",
          "dsf_disinfectantname": "VanguardGuard",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "280",
          "dsf_fm_approveddilution": "390",
          "dsf_go_approveddilution": "500",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "VanguardGuard",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "610",
          "dsf_tb_approveddilution": "720",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05da",
          "dsf_chemicalgroups": "Peracetic acid; Quaternary ammonium compounds",
          "dsf_companyaddress": "20 Commerce Road, Tradeville, TV20 20TT",
          "dsf_companyname": "Wellness Corp",
          "dsf_disinfectant": "WellnessClean",
          "dsf_disinfectantname": "WellnessClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "290",
          "dsf_fm_approveddilution": "400",
          "dsf_go_approveddilution": "510",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "WellnessClean",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "620",
          "dsf_tb_approveddilution": "730",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05db",
          "dsf_chemicalgroups": "Hydrogen peroxide; Chlorine dioxide",
          "dsf_companyaddress": "21 Industrial Lane, Manufacture City, MC21 21UU",
          "dsf_companyname": "XtraGuard Inc",
          "dsf_disinfectant": "XtraClean",
          "dsf_disinfectantname": "XtraClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "300",
          "dsf_fm_approveddilution": "410",
          "dsf_go_approveddilution": "520",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "XtraClean",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "630",
          "dsf_tb_approveddilution": "740",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05dc",
          "dsf_chemicalgroups": "Peracetic acid; Quaternary ammonium compounds",
          "dsf_companyaddress": "22 Biotech Drive, Innovation Town, IT22 22VV",
          "dsf_companyname": "Yield Solutions",
          "dsf_disinfectant": "YieldGuard",
          "dsf_disinfectantname": "YieldGuard",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "310",
          "dsf_fm_approveddilution": "420",
          "dsf_go_approveddilution": "530",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "YieldGuard",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "640",
          "dsf_tb_approveddilution": "750",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05d0",
          "dsf_chemicalgroups": "Peracetic acid; Quaternary ammonium compounds",
          "dsf_companyaddress": "10 Tech Hub, Innovatown, IT10 10JJ",
          "dsf_companyname": "LambdaLabs",
          "dsf_disinfectant": "LambdaClean",
          "dsf_disinfectantname": "LambdaClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "190",
          "dsf_fm_approveddilution": "300",
          "dsf_go_approveddilution": "410",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "LambdaClean",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "520",
          "dsf_tb_approveddilution": "630",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05e1",
          "dsf_chemicalgroups": "Peracetic acid; Chlorine dioxide",
          "dsf_companyaddress": "12 Central Avenue, MidCity, MC12 12LL",
          "dsf_companyname": "Central BioSolutions",
          "dsf_disinfectant": "CentralClean",
          "dsf_disinfectantname": "CentralClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "210",
          "dsf_fm_approveddilution": "320",
          "dsf_go_approveddilution": "430",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "CentralClean",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "540",
          "dsf_tb_approveddilution": "650",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05h3",
          "dsf_chemicalgroups": "Hydrogen peroxide; Phenolic compounds",
          "dsf_companyaddress": "13 Forest Drive, GreenTown, GT13 13MM",
          "dsf_companyname": "ForestGuard Ltd",
          "dsf_disinfectant": "ForestClean",
          "dsf_disinfectantname": "ForestClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "220",
          "dsf_fm_approveddilution": "330",
          "dsf_go_approveddilution": "440",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "ForestClean",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "550",
          "dsf_tb_approveddilution": "660",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05h4",
          "dsf_chemicalgroups": "Peracetic acid; Hydrogen peroxide",
          "dsf_companyaddress": "14 Harbor Road, CoastalCity, CC14 14NN",
          "dsf_companyname": "Harbor Solutions",
          "dsf_disinfectant": "HarborClean",
          "dsf_disinfectantname": "HarborClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "230",
          "dsf_fm_approveddilution": "340",
          "dsf_go_approveddilution": "450",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "HarborClean",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "560",
          "dsf_tb_approveddilution": "670",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05h5",
          "dsf_chemicalgroups": "Sodium hypochlorite; Quaternary ammonium compounds",
          "dsf_companyaddress": "15 Innovation Way, TechHub, TH15 15OO",
          "dsf_companyname": "Innovative BioTech",
          "dsf_disinfectant": "InnovativeClean",
          "dsf_disinfectantname": "InnovativeClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "240",
          "dsf_fm_approveddilution": "350",
          "dsf_go_approveddilution": "460",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "InnovativeClean",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "570",
          "dsf_tb_approveddilution": "680",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05h6",
          "dsf_chemicalgroups": "Peracetic acid; Chlorine dioxide",
          "dsf_companyaddress": "16 Jetstream Drive, SkyCity, SC16 16PP",
          "dsf_companyname": "Jetstream Technologies",
          "dsf_disinfectant": "JetClean",
          "dsf_disinfectantname": "JetClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "250",
          "dsf_fm_approveddilution": "360",
          "dsf_go_approveddilution": "470",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "JetClean",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "580",
          "dsf_tb_approveddilution": "690",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05h7",
          "dsf_chemicalgroups": "Hydrogen peroxide; Phenolic compounds",
          "dsf_companyaddress": "17 Metro Lane, UrbanTown, UT17 17QQ",
          "dsf_companyname": "MetroBio Inc",
          "dsf_disinfectant": "MetroClean",
          "dsf_disinfectantname": "MetroClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "260",
          "dsf_fm_approveddilution": "370",
          "dsf_go_approveddilution": "480",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "MetroClean",
          "dsf_pform": "Liquid",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "590",
          "dsf_tb_approveddilution": "700",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      },
      {
          "createdon": "2024-04-26T10:32:36Z",
          "dsf_approvalslistsiid": "0abae34a-b803-ef11-9f89-000d3a0d05h8",
          "dsf_chemicalgroups": "Sodium hypochlorite; Quaternary ammonium compounds",
          "dsf_companyaddress": "18 Tech Park, InnovateCity, IC18 18RR",
          "dsf_companyname": "TechGuard Solutions",
          "dsf_disinfectant": "TechClean",
          "dsf_disinfectantname": "TechClean",
          "dsf_disinfectanttype": 1,
          "dsf_dp_approveddilution": "270",
          "dsf_fm_approveddilution": "380",
          "dsf_go_approveddilution": "490",
          "dsf_identity": null,
          "dsf_parentdisinfectant": "TechClean",
          "dsf_pform": "Powder",
          "dsf_pid": null,
          "dsf_sv_approveddilution": "600",
          "dsf_tb_approveddilution": "710",
          "dsf_tradenameordisinfectantname": "Yes",
          "statecode": 0,
          "statuscode": 1
      }
  ]
};

const findAllDocuments = {
  handler: async (request, h) => {
    try {
      const entities = await readAllDocuments(request.db, disinfectantApprovedListSI)

      return h.response({ message: 'success', entities }).code(200)
    } catch (error) {
      return h.response({ error: error.message }).code(500)
    }
  }
}

const findDocument = {
  handler: async (request, h) => {
    const { id } = request.params
    try {
      const entity = await readDocument(request.db, disinfectantApprovedListSI, {
        _id: id
      })

      if (entity) {
        return h.response({ message: 'success', entity }).code(200)
      } else {
        return h.response({ error: 'Entity not found' }).code(404)
      }
    } catch (error) {
      return h.response({ error: error.message }).code(500)
    }
  }
}

const saveDocument = {
  handler: async (request, h) => {
    // const { error, value: payload } = contactSchema.validate(request.payload)
    // if (error) {
    //   return h.response({ error: error.details[0].message }).code(400)
    // }
    try {
      const entity = await createDocument(request.db, disinfectantApprovedListSI, sampleData)
      return h.response({ message: 'success', entity }).code(201)
    } catch (error) {
      return h.response({ error: error.message }).code(500)
    }
  }
}

export { findAllDocuments, findDocument, saveDocument }